version: 2
updates:
  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - terraform

  - package-ecosystem: terraform
    directory: /modules/network
    schedule:
      interval: weekly
    labels:
      - dependencies
      - terraform

  - package-ecosystem: terraform
    directory: /modules/alb
    schedule:
      interval: weekly
    labels:
      - dependencies
      - terraform

  - package-ecosystem: terraform
    directory: /modules/worker
    schedule:
      interval: weekly
    labels:
      - dependencies
      - terraform

  - package-ecosystem: terraform
    directory: /modules/storage
    schedule:
      interval: weekly
    labels:
      - dependencies
      - terraform

  - package-ecosystem: terraform
    directory: /modules/observability
    schedule:
      interval: weekly
    labels:
      - dependencies
      - terraform

  - package-ecosystem: pip
    directory: /worker
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - python
      - worker
    allow:
      - dependency-type: direct
      - dependency-type: indirect

  - package-ecosystem: docker
    directory: /worker
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - github-actions
